;=========================================================
;		This file includes the instructions' names
;=========================================================

.const
InstructionsTable 	equ offset InstructionsTable1


InstructionsTable1	  dd	 Inst_00,
	 Inst_01,	 Inst_02,	 Inst_03,
	 Inst_04,	 Inst_05,	 Inst_06,
	 Inst_07,	 Inst_08,	 Inst_09,
	 Inst_0A,	 Inst_0B,	 Inst_0C,
	 Inst_0D,	 Inst_0E,	 Inst_0F,
	 Inst_10,	 Inst_11,	 Inst_12,
	 Inst_13,	 Inst_14,	 Inst_15,
	 Inst_16,	 Inst_17,	 Inst_18,
	 Inst_19,	 Inst_1A,	 Inst_1B,
	 Inst_1C,	 Inst_1D,	 Inst_1E,
	 Inst_1F,	 Inst_20,	 Inst_21,
	 Inst_22,	 Inst_23,	 Inst_24

dd	 Inst_25,	 Inst_26,	 Inst_27,
	 Inst_28,	 Inst_29,	 Inst_2A,
	 Inst_2B,	 Inst_2C,	 Inst_2D,
	 Inst_2E,	 Inst_2F,	 Inst_30,
	 Inst_31,	 Inst_32,	 Inst_33,
	 Inst_34,	 Inst_35,	 Inst_36,
	 Inst_37,	 Inst_38,	 Inst_39,
	 Inst_3A,	 Inst_3B,	 Inst_3C,
	 Inst_3D,	 Inst_3E,	 Inst_3F,
	 Inst_40,	 Inst_41,	 Inst_42,
	 Inst_43,	 Inst_44,	 Inst_45,
	 Inst_46,	 Inst_47,	 Inst_48

dd	 Inst_49,	 Inst_4A,	 Inst_4B,
	 Inst_4C,	 Inst_4D,	 Inst_4E,
	 Inst_4F,	 Inst_50,	 Inst_51,
	 Inst_52,	 Inst_53,	 Inst_54,
	 Inst_55,	 Inst_56,	 Inst_57,
	 Inst_58,	 Inst_59,	 Inst_5A,
	 Inst_5B,	 Inst_5C,	 Inst_5D,
	 Inst_5E,	 Inst_5F,	 Inst_60,
	 Inst_61,	 Inst_62,	 Inst_63,
	 Inst_64,	 Inst_65,	 Inst_66,
	 Inst_67,	 Inst_68,	 Inst_69,
	 Inst_6A,	 Inst_6B,	 Inst_6C

dd	 Inst_6D,	 Inst_6E,	 Inst_6F,
	 Inst_70,	 Inst_71,	 Inst_72,
	 Inst_73,	 Inst_74,	 Inst_75,
	 Inst_76,	 Inst_77,	 Inst_78,
	 Inst_79,	 Inst_7A,	 Inst_7B,
	 Inst_7C,	 Inst_7D,	 Inst_7E,
	 Inst_7F,	 Inst_80,	 Inst_81,
	 Inst_82,	 Inst_83,	 Inst_84,
	 Inst_85,	 Inst_86,	 Inst_87,
	 Inst_88,	 Inst_89,	 Inst_8A,
	 Inst_8B,	 Inst_8C,	 Inst_8D,
	 Inst_8E,	 Inst_8F,	 Inst_90

dd	 Inst_91,	 Inst_92,	 Inst_93,
	 Inst_94,	 Inst_95,	 Inst_96,
	 Inst_97,	 Inst_98,	 Inst_99,
	 Inst_9A,	 Inst_9B,	 Inst_9C,
	 Inst_9D,	 Inst_9E,	 Inst_9F,
	 Inst_A0,	 Inst_A1,	 Inst_A2,
	 Inst_A3,	 Inst_A4,	 Inst_A5,
	 Inst_A6,	 Inst_A7,	 Inst_A8,
	 Inst_A9,	 Inst_AA,	 Inst_AB,
	 Inst_AC,	 Inst_AD,	 Inst_AE,
	 Inst_AF,	 Inst_B0,	 Inst_B1,
	 Inst_B2,	 Inst_B3,	 Inst_B4

dd	 Inst_B5,	 Inst_B6,	 Inst_B7,
	 Inst_B8,	 Inst_B9,	 Inst_BA,
	 Inst_BB,	 Inst_BC,	 Inst_BD,
	 Inst_BE,	 Inst_BF,	 Inst_C0,
	 Inst_C1,	 Inst_C2,	 Inst_C3,
	 Inst_C4,	 Inst_C5,	 Inst_C6,
	 Inst_C7,	 Inst_C8,	 Inst_C9,
	 Inst_CA,	 Inst_CB,	 Inst_CC,
	 Inst_CD,	 Inst_CE,	 Inst_CF,
	 Inst_D0,	 Inst_D1,	 Inst_D2,
	 Inst_D3,	 Inst_D4,	 Inst_D5,
	 Inst_D6,	 Inst_D7,	 Inst_D8

dd	 Inst_D9,	 Inst_DA,	 Inst_DB,
	 Inst_DC,	 Inst_DD,	 Inst_DE,
	 Inst_DF,	 Inst_E0,	 Inst_E1,
	 Inst_E2,	 Inst_E3,	 Inst_E4,
	 Inst_E5,	 Inst_E6,	 Inst_E7,
	 Inst_E8,	 Inst_E9,	 Inst_EA,
	 Inst_EB,	 Inst_EC,	 Inst_ED,
	 Inst_EE,	 Inst_EF,	 Inst_F0,
	 Inst_F1,	 Inst_F2,	 Inst_F3,
	 Inst_F4,	 Inst_F5,	 Inst_F6,
	 Inst_F7,	 Inst_F8,	 Inst_F9,
	 Inst_FA,	 Inst_FB,	 Inst_FC

dd	 Inst_FD,	 Inst_FE,	 Inst_FF

.data

	Inst_00	db	"ADD",0
	Inst_01	db	"ADD",0
	Inst_02	db	"ADD",0
	Inst_03	db	"ADD",0
	Inst_04	db	"ADD",0
	Inst_05	db	"ADD",0
	Inst_06	db	"PUSH ES",0
	Inst_07	db	"POP ES",0
	Inst_08	db	"OR",0
	Inst_09	db	"OR",0
	Inst_0A	db	"OR",0
	Inst_0B	db	"OR",0
	Inst_0C	db	"OR",0
	Inst_0D	db	"OR",0
	Inst_0E	db	"PUSH CS",0
	Inst_0F	db	"NEW OPCODE",0
	Inst_10	db	"ADC",0
	Inst_11	db	"ADC",0
	Inst_12	db	"ADC",0
	Inst_13	db	"ADC",0
	Inst_14	db	"ADC",0
	Inst_15	db	"ADC",0
	Inst_16	db	"PUSH SS",0
	Inst_17	db	"POP SS",0
	Inst_18	db	"SBB",0
	Inst_19	db	"SBB",0
	Inst_1A	db	"SBB",0
	Inst_1B	db	"SBB",0
	Inst_1C	db	"SBB",0
	Inst_1D	db	"SBB",0
	Inst_1E	db	"PUSH DS",0
	Inst_1F	db	"POP DS",0
	Inst_20	db	"AND",0
	Inst_21	db	"AND",0
	Inst_22	db	"AND",0
	Inst_23	db	"AND",0
	Inst_24	db	"AND",0
	Inst_25	db	"AND",0
	Inst_26	db	"SEGMENT OVERRIDE PREFIX",0
	Inst_27	db	"DAA",0
	Inst_28	db	"SUB",0
	Inst_29	db	"SUB",0
	Inst_2A	db	"SUB",0
	Inst_2B	db	"SUB",0
	Inst_2C	db	"SUB",0
	Inst_2D	db	"SUB",0
	Inst_2E	db	"SEGMENT OVERRIDE PREFIX",0
	Inst_2F	db	"DAS",0
	Inst_30	db	"XOR",0
	Inst_31	db	"XOR",0
	Inst_32	db	"XOR",0
	Inst_33	db	"XOR",0
	Inst_34	db	"XOR",0
	Inst_35	db	"XOR",0
	Inst_36	db	"SEGMENT OVERRIDE PREFIX",0
	Inst_37	db	"AAA",0
	Inst_38	db	"CMP",0
	Inst_39	db	"CMP",0
	Inst_3A	db	"CMP",0
	Inst_3B	db	"CMP",0
	Inst_3C	db	"CMP",0
	Inst_3D	db	"CMP",0
	Inst_3E	db	"SEGMENT OVERRIDE PREFIX",0
	Inst_3F	db	"AAS",0
	Inst_40	db	"INC",0
	Inst_41	db	"INC",0
	Inst_42	db	"INC",0
	Inst_43	db	"INC",0
	Inst_44	db	"INC",0
	Inst_45	db	"INC",0
	Inst_46	db	"INC",0
	Inst_47	db	"INC",0
	Inst_48	db	"DEC",0
	Inst_49	db	"DEC",0
	Inst_4A	db	"DEC",0
	Inst_4B	db	"DEC",0
	Inst_4C	db	"DEC",0
	Inst_4D	db	"DEC",0
	Inst_4E	db	"DEC",0
	Inst_4F	db	"DEC",0
	Inst_50	db	"PUSH",0
	Inst_51	db	"PUSH",0
	Inst_52	db	"PUSH",0
	Inst_53	db	"PUSH",0
	Inst_54	db	"PUSH",0
	Inst_55	db	"PUSH",0
	Inst_56	db	"PUSH",0
	Inst_57	db	"PUSH",0
	Inst_58	db	"POP",0
	Inst_59	db	"POP",0
	Inst_5A	db	"POP",0
	Inst_5B	db	"POP",0
	Inst_5C	db	"POP",0
	Inst_5D	db	"POP",0
	Inst_5E	db	"POP",0
	Inst_5F	db	"POP",0
	Inst_60	db	"PUSHAD",0
	Inst_61	db	"POPAD",0
	Inst_62	db	"BOUND",0
	Inst_63	db	"ARPL",0
	Inst_64	db	"SEGMENT OVERRIDE PREFIX",0
	Inst_65	db	"SEGMENT OVERRIDE PREFIX",0
	Inst_66	db	"OPERAND SIZE OVERRIDE PREFIX",0
	Inst_67	db	"ADDRESS SIZE OVERRIDE PREFIX",0
	Inst_68	db	"PUSH",0
	Inst_69	db	"IMUL",0
	Inst_6A	db	"PUSH",0
	Inst_6B	db	"IMUL",0
	Inst_6C	db	"INS",0
	Inst_6D	db	"INS",0
	Inst_6E	db	"OUTS",0
	Inst_6F	db	"OUTS",0
	Inst_70	db	"JO",0
	Inst_71	db	"JNO",0
	Inst_72	db	"JC",0
	Inst_73	db	"JAE",0
	Inst_74	db	"JE",0
	Inst_75	db	"JNE",0
	Inst_76	db	"JBE",0
	Inst_77	db	"JA",0
	Inst_78	db	"JS",0
	Inst_79	db	"JNS",0
	Inst_7A	db	"JPE",0
	Inst_7B	db	"JPO",0
	Inst_7C	db	"JL",0
	Inst_7D	db	"JGE",0
	Inst_7E	db	"JLE",0
	Inst_7F	db	"JG",0
	Inst_80	db	"ADD",0, "OR",0 , "ADC",0, "SBB",0, "AND",0, "SUB",0, "XOR",0, "CMP",0
	Inst_81	db	"ADD",0, "OR",0, "ADC",0, "SBB",0, "AND",0, "SUB",0, "XOR",0, "CMP",0
	Inst_82	db	"??",0
	Inst_83	db	"ADD",0, "OR",0, "ADC",0, "SBB",0, "AND",0, "SUB",0, "XOR",0, "CMP",0
	Inst_84	db	"TEST",0
	Inst_85	db	"TEST",0
	Inst_86	db	"XCHG",0
	Inst_87	db	"XCHG",0
	Inst_88	db	"MOV",0
	Inst_89	db	"MOV",0
	Inst_8A	db	"MOV",0
	Inst_8B	db	"MOV",0
	Inst_8C	db	"MOV",0
	Inst_8D	db	"LEA",0
	Inst_8E	db	"MOV",0
	Inst_8F	db	"POP",0
	Inst_90	db	"NOP",0
	Inst_91	db	"XCHG",0
	Inst_92	db	"XCHG",0
	Inst_93	db	"XCHG",0
	Inst_94	db	"XCHG",0
	Inst_95	db	"XCHG",0
	Inst_96	db	"XCHG",0
	Inst_97	db	"XCHG",0
	Inst_98	db	"CBW",0
	Inst_99	db	"CDQ",0, "CWD", 0
	Inst_9A	db	"CALL",0
	Inst_9B	db	"FWAIT",0, "WAIT",0, "FSTENV",0, "FSTCW",0, "FCLEX",0, "FINIT",0,
				"FSAVE",0, "FSTSW",0, "FSTSW AX",0
	Inst_9C	db	"PUSHFD",0
	Inst_9D	db	"POPFD",0
	Inst_9E	db	"SAHF",0
	Inst_9F	db	"LAHF",0
	Inst_A0	db	"MOV",0
	Inst_A1	db	"MOV",0
	Inst_A2	db	"MOV",0
	Inst_A3	db	"MOVS",0
	Inst_A4	db	"MOV",0
	Inst_A5	db	"MOV",0
	Inst_A6	db	"CMPSB",0
	Inst_A7	db	"CMPSD",0
	Inst_A8	db	"TEST",0
	Inst_A9	db	"TEST",0
	Inst_AA	db	"STOS",0
	Inst_AB	db	"STOS",0
	Inst_AC	db	"LODS",0
	Inst_AD	db	"LODS",0
	Inst_AE	db	"SCAS",0
	Inst_AF	db	"SCAS",0
	Inst_B0	db	"MOV",0
	Inst_B1	db	"MOV",0
	Inst_B2	db	"MOV",0
	Inst_B3	db	"MOV",0
	Inst_B4	db	"MOV",0
	Inst_B5	db	"MOV",0
	Inst_B6	db	"MOV",0
	Inst_B7	db	"MOV",0
	Inst_B8	db	"MOV",0
	Inst_B9	db	"MOV",0
	Inst_BA	db	"MOV",0
	Inst_BB	db	"MOV",0
	Inst_BC	db	"MOV",0
	Inst_BD	db	"MOV",0
	Inst_BE	db	"MOV",0
	Inst_BF	db	"MOV",0
	Inst_C0	db	"ROL",0,"ROR",0, "RCL",0, "RCR",0, "SAL",0, "SHL",0, "SHR",0, "SAR",0
	Inst_C1	db	"ROL",0,"ROR",0, "RCL",0, "RCR",0, "SAL",0, "SHL",0, "SHR",0, "SAR",0
	Inst_C2	db	"RET",0
	Inst_C3	db	"RET",0
	Inst_C4	db	"LES",0
	Inst_C5	db	"LDS",0
	Inst_C6	db	"MOV",0
	Inst_C7	db	"MOV",0
	Inst_C8	db	"ENTER",0
	Inst_C9	db	"LEAVE",0
	Inst_CA	db	"RET",0
	Inst_CB	db	"RET",0
	Inst_CC	db	"INT 3",0
	Inst_CD	db	"INT",0
	Inst_CE	db	"INTO",0
	Inst_CF	db	"IRETD",0
	Inst_D0	db	"ROL",0,"ROR",0, "RCL",0, "RCR",0, "SAL",0, "SHL",0, "SHR",0, "SAR"
	Inst_D1	db	"ROL",0,"ROR",0, "RCL",0, "RCR",0, "SAL",0, "SHL",0, "SHR",0, "SAR"
	Inst_D2	db	"ROL",0,"ROR",0, "RCL",0, "RCR",0, "SAL",0, "SHL",0, "SHR",0, "SAR"
	Inst_D3	db	"ROL",0,"ROR",0, "RCL",0, "RCR",0, "SAL",0, "SHL",0, "SHR",0, "SAR"
	Inst_D4	db	"AAM",0
	Inst_D5	db	"AAD",0
	Inst_D6	db	"SETALC",0
	Inst_D7	db	"XLAT",0
	Inst_D8	db	"FADD",0, "FMUL",0, "FCOM",0, "FCOMP",0, "FSUB",0, "FSUBR",0, "FDIV",0, "DIVR"
	Inst_D9	db	"ALOT OF FPU",0
	Inst_DA	db	"ALOT OF FPU",0
	Inst_DB	db	"ALOT OF FPU",0
	Inst_DC	db	"ALOT OF FPU",0
	Inst_DD	db	"ALOT OF FPU",0
	Inst_DE	db	"ALOT OF FPU",0
	Inst_DF	db	"ALOT OF FPU",0
	Inst_E0	db	"LOOPNE",0
	Inst_E1	db	"LOOPE",0
	Inst_E2	db	"LOOP",0
	Inst_E3	db	"JECXZ",0
	Inst_E4	db	"IN",0
	Inst_E5	db	"IN",0
	Inst_E6	db	"OUT",0
	Inst_E7	db	"OUT",0
	Inst_E8	db	"CALL",0
	Inst_E9	db	"JMP",0
	Inst_EA	db	"JMP",0
	Inst_EB	db	"JMP",0
	Inst_EC	db	"IN",0
	Inst_ED	db	"IN",0
	Inst_EE	db	"OUT",0
	Inst_EF	db	"OUT",0
	Inst_F0	db	"LOCK",0
	Inst_F1	db	"INT 1",0
	Inst_F2	db	"REPNE CMPS",0,"REPNE CMPS",0,"REPNE SCAS",0,"REPNE SCAS",0
	Inst_F3	db	"REP INS",0,"REP INS",0,"REP OUTS",0,"REP OUTS",0,"REP MOVS",0,
				"REP MOVS",0,"REP CMPS",0,"REP CMPS",0,"REP STOS",0,"REP STOS",0,
				"REP LODS",0,"REP LODS",0,"REP SCAS",0,"REP SCAS",0
	Inst_F4	db	"HLT",0
	Inst_F5	db	"CMC",0
	Inst_F6	db	"NOT",0 ,"NEG",0,"MUL",0,"IMUL",0,"DIV",0,"IDIV",0,"TEST",0
	Inst_F7	db	"NOT",0 ,"NEG",0,"MUL",0,"IMUL",0,"DIV",0,"IDIV",0,"TEST",0
	Inst_F8	db	"CLC",0
	Inst_F9	db	"STC",0
	Inst_FA	db	"CLI",0
	Inst_FB	db	"STI",0
	Inst_FC	db	"CLD",0
	Inst_FD	db	"STD",0
	Inst_FE	db	"INC",0, "DEC",0
	Inst_FF	db	"INC",0, "DEC",0, "CALL",0, "CALL",0, "JMP",0, "PUSH",0, "JMP",0
