.data

OpcodesTable	dd 		Opcode00, Opcode01, Opcode02, Opcode03, 
						Opcode04, Opcode05, Opcode06, Opcode07, 
						Opcode08, Opcode09, Opcode0A, Opcode0B, 
						Opcode0C, Opcode0D, Opcode0E, Opcode0F, 
						Opcode10, Opcode11, Opcode12, Opcode13, 
						Opcode14, Opcode15, Opcode16, Opcode17, 
						Opcode18, Opcode19, Opcode1A, Opcode1B, 
						Opcode1C, Opcode1D, Opcode1E, Opcode1F, 
						Opcode20, Opcode21, Opcode22, Opcode23, 
						Opcode24, Opcode25, Opcode26, Opcode27
						
				dd 		Opcode28, Opcode29, Opcode2A, Opcode2B, 
						Opcode2C, Opcode2D, Opcode2E, Opcode2F, 
						Opcode30, Opcode31, Opcode32, Opcode33, 
						Opcode34, Opcode35, Opcode36, Opcode37, 
						Opcode38, Opcode39, Opcode3A, Opcode3B, 
						Opcode3C, Opcode3D, Opcode3E, Opcode3F, 
						Opcode40, Opcode41, Opcode42, Opcode43, 
						Opcode44, Opcode45, Opcode46, Opcode47, 
						Opcode48, Opcode49, Opcode4A, Opcode4B, 
						Opcode4C, Opcode4D, Opcode4E, Opcode4F
						
				dd 		Opcode50, Opcode51, Opcode52, Opcode53, 
						Opcode54, Opcode55, Opcode56, Opcode57, 
						Opcode58, Opcode59, Opcode5A, Opcode5B, 
						Opcode5C, Opcode5D, Opcode5E, Opcode5F, 
						Opcode60, Opcode61, Opcode62, Opcode63, 
						Opcode64, Opcode65, Opcode66, Opcode67, 
						Opcode68, Opcode69, Opcode6A, Opcode6B, 
						Opcode6C, Opcode6D, Opcode6E, Opcode6F, 
						Opcode70, Opcode71, Opcode72, Opcode73, 
						Opcode74, Opcode75, Opcode76, Opcode77
						
				dd 		Opcode78, Opcode79, Opcode7A, Opcode7B, 
						Opcode7C, Opcode7D, Opcode7E, Opcode7F, 
						Opcode80, Opcode81, Opcode82, Opcode83, 
						Opcode84, Opcode85, Opcode86, Opcode87, 
						Opcode88, Opcode89, Opcode8A, Opcode8B, 
						Opcode8C, Opcode8D, Opcode8E, Opcode8F, 
						Opcode90, Opcode91, Opcode92, Opcode93, 
						Opcode94, Opcode95, Opcode96, Opcode97, 
						Opcode98, Opcode99, Opcode9A, Opcode9B, 
						Opcode9C, Opcode9D, Opcode9E, Opcode9F
						
				dd 		OpcodeA0, OpcodeA1, OpcodeA2, OpcodeA3, 
						OpcodeA4, OpcodeA5, OpcodeA6, OpcodeA7, 
						OpcodeA8, OpcodeA9, OpcodeAA, OpcodeAB, 
						OpcodeAC, OpcodeAD, OpcodeAE, OpcodeAF, 
						OpcodeB0, OpcodeB1, OpcodeB2, OpcodeB3, 
						OpcodeB4, OpcodeB5, OpcodeB6, OpcodeB7, 
						OpcodeB8, OpcodeB9, OpcodeBA, OpcodeBB, 
						OpcodeBC, OpcodeBD, OpcodeBE, OpcodeBF, 
						OpcodeC0, OpcodeC1, OpcodeC2, OpcodeC3, 
						OpcodeC4, OpcodeC5, OpcodeC6, OpcodeC7 
						
				dd 		OpcodeC8, OpcodeC9, OpcodeCA, OpcodeCB, 
						OpcodeCC, OpcodeCD, OpcodeCE, OpcodeCF, 
						OpcodeD0, OpcodeD1, OpcodeD2, OpcodeD3, 
						OpcodeD4, OpcodeD5, OpcodeD6, OpcodeD7, 
						OpcodeD8, OpcodeD9, OpcodeDA, OpcodeDB, 
						OpcodeDC, OpcodeDD, OpcodeDE, OpcodeDF, 
						OpcodeE0, OpcodeE1, OpcodeE2, OpcodeE3, 
						OpcodeE4, OpcodeE5, OpcodeE6, OpcodeE7, 
						OpcodeE8, OpcodeE9, OpcodeEA, OpcodeEB, 
						OpcodeEC, OpcodeED, OpcodeEE, OpcodeEF
						
				dd 		OpcodeF0, OpcodeF1, OpcodeF2, OpcodeF3, 
						OpcodeF4, OpcodeF5, OpcodeF6, OpcodeF7, 
						OpcodeF8, OpcodeF9, OpcodeFA, OpcodeFB, 
						OpcodeFC, OpcodeFD, OpcodeFE, OpcodeFF
						
					
.code

; ------------ Opcode 0x00 ----------------
Opcode00 proc
	ret
Opcode00 endp
; -----------------------------------------
; ------------ Opcode 0x01 ----------------
Opcode01 proc

	ret
Opcode01 endp
; -----------------------------------------
; ------------ Opcode 0x02 ----------------
Opcode02 proc

	ret
Opcode02 endp
; -----------------------------------------
; ------------ Opcode 0x03 ----------------
Opcode03 proc

	ret
Opcode03 endp
; -----------------------------------------
; ------------ Opcode 0x04 ----------------
Opcode04 proc

	ret
Opcode04 endp
; -----------------------------------------
; ------------ Opcode 0x05 ----------------
Opcode05 proc

	ret
Opcode05 endp
; -----------------------------------------
; ------------ Opcode 0x06 ----------------
Opcode06 proc

	ret
Opcode06 endp
; -----------------------------------------
; ------------ Opcode 0x07 ----------------
Opcode07 proc

	ret
Opcode07 endp
; -----------------------------------------
; ------------ Opcode 0x08 ----------------
Opcode08 proc

	ret
Opcode08 endp
; -----------------------------------------
; ------------ Opcode 0x09 ----------------
Opcode09 proc

	ret
Opcode09 endp
; -----------------------------------------
; ------------ Opcode 0x0A ----------------
Opcode0A proc

	ret
Opcode0A endp
; -----------------------------------------
; ------------ Opcode 0x0B ----------------
Opcode0B proc

	ret
Opcode0B endp
; -----------------------------------------
; ------------ Opcode 0x0C ----------------
Opcode0C proc

	ret
Opcode0C endp
; -----------------------------------------
; ------------ Opcode 0x0D ----------------
Opcode0D proc

	ret
Opcode0D endp
; -----------------------------------------
; ------------ Opcode 0x0E ----------------
Opcode0E proc

	ret
Opcode0E endp
; -----------------------------------------
; ------------ Opcode 0x0F ----------------
Opcode0F proc

	ret
Opcode0F endp
; -----------------------------------------
; ------------ Opcode 0x10 ----------------
Opcode10 proc

	ret
Opcode10 endp
; -----------------------------------------
; ------------ Opcode 0x11 ----------------
Opcode11 proc

	ret
Opcode11 endp
; -----------------------------------------
; ------------ Opcode 0x12 ----------------
Opcode12 proc

	ret
Opcode12 endp
; -----------------------------------------
; ------------ Opcode 0x13 ----------------
Opcode13 proc

	ret
Opcode13 endp
; -----------------------------------------
; ------------ Opcode 0x14 ----------------
Opcode14 proc

	ret
Opcode14 endp
; -----------------------------------------
; ------------ Opcode 0x15 ----------------
Opcode15 proc

	ret
Opcode15 endp
; -----------------------------------------
; ------------ Opcode 0x16 ----------------
Opcode16 proc

	ret
Opcode16 endp
; -----------------------------------------
; ------------ Opcode 0x17 ----------------
Opcode17 proc

	ret
Opcode17 endp
; -----------------------------------------
; ------------ Opcode 0x18 ----------------
Opcode18 proc

	ret
Opcode18 endp
; -----------------------------------------
; ------------ Opcode 0x19 ----------------
Opcode19 proc

	ret
Opcode19 endp
; -----------------------------------------
; ------------ Opcode 0x1A ----------------
Opcode1A proc

	ret
Opcode1A endp
; -----------------------------------------
; ------------ Opcode 0x1B ----------------
Opcode1B proc

	ret
Opcode1B endp
; -----------------------------------------
; ------------ Opcode 0x1C ----------------
Opcode1C proc

	ret
Opcode1C endp
; -----------------------------------------
; ------------ Opcode 0x1D ----------------
Opcode1D proc

	ret
Opcode1D endp
; -----------------------------------------
; ------------ Opcode 0x1E ----------------
Opcode1E proc

	ret
Opcode1E endp
; -----------------------------------------
; ------------ Opcode 0x1F ----------------
Opcode1F proc

	ret
Opcode1F endp
; -----------------------------------------
; ------------ Opcode 0x20 ----------------
Opcode20 proc

	ret
Opcode20 endp
; -----------------------------------------
; ------------ Opcode 0x21 ----------------
Opcode21 proc

	ret
Opcode21 endp
; -----------------------------------------
; ------------ Opcode 0x22 ----------------
Opcode22 proc

	ret
Opcode22 endp
; -----------------------------------------
; ------------ Opcode 0x23 ----------------
Opcode23 proc

	ret
Opcode23 endp
; -----------------------------------------
; ------------ Opcode 0x24 ----------------
Opcode24 proc

	ret
Opcode24 endp
; -----------------------------------------
; ------------ Opcode 0x25 ----------------
Opcode25 proc

	ret
Opcode25 endp
; -----------------------------------------
; ------------ Opcode 0x26 ----------------
Opcode26 proc

	ret
Opcode26 endp
; -----------------------------------------
; ------------ Opcode 0x27 ----------------
Opcode27 proc

	ret
Opcode27 endp
; -----------------------------------------
; ------------ Opcode 0x28 ----------------
Opcode28 proc

	ret
Opcode28 endp
; -----------------------------------------
; ------------ Opcode 0x29 ----------------
Opcode29 proc

	ret
Opcode29 endp
; -----------------------------------------
; ------------ Opcode 0x2A ----------------
Opcode2A proc

	ret
Opcode2A endp
; -----------------------------------------
; ------------ Opcode 0x2B ----------------
Opcode2B proc

	ret
Opcode2B endp
; -----------------------------------------
; ------------ Opcode 0x2C ----------------
Opcode2C proc

	ret
Opcode2C endp
; -----------------------------------------
; ------------ Opcode 0x2D ----------------
Opcode2D proc

	ret
Opcode2D endp
; -----------------------------------------
; ------------ Opcode 0x2E ----------------
Opcode2E proc

	ret
Opcode2E endp
; -----------------------------------------
; ------------ Opcode 0x2F ----------------
Opcode2F proc

	ret
Opcode2F endp
; -----------------------------------------
; ------------ Opcode 0x30 ----------------
Opcode30 proc

	ret
Opcode30 endp
; -----------------------------------------
; ------------ Opcode 0x31 ----------------
Opcode31 proc

	ret
Opcode31 endp
; -----------------------------------------
; ------------ Opcode 0x32 ----------------
Opcode32 proc

	ret
Opcode32 endp
; -----------------------------------------
; ------------ Opcode 0x33 ----------------
Opcode33 proc

	ret
Opcode33 endp
; -----------------------------------------
; ------------ Opcode 0x34 ----------------
Opcode34 proc

	ret
Opcode34 endp
; -----------------------------------------
; ------------ Opcode 0x35 ----------------
Opcode35 proc

	ret
Opcode35 endp
; -----------------------------------------
; ------------ Opcode 0x36 ----------------
Opcode36 proc

	ret
Opcode36 endp
; -----------------------------------------
; ------------ Opcode 0x37 ----------------
Opcode37 proc

	ret
Opcode37 endp
; -----------------------------------------
; ------------ Opcode 0x38 ----------------
Opcode38 proc

	ret
Opcode38 endp
; -----------------------------------------
; ------------ Opcode 0x39 ----------------
Opcode39 proc

	ret
Opcode39 endp
; -----------------------------------------
; ------------ Opcode 0x3A ----------------
Opcode3A proc

	ret
Opcode3A endp
; -----------------------------------------
; ------------ Opcode 0x3B ----------------
Opcode3B proc

	ret
Opcode3B endp
; -----------------------------------------
; ------------ Opcode 0x3C ----------------
Opcode3C proc

	ret
Opcode3C endp
; -----------------------------------------
; ------------ Opcode 0x3D ----------------
Opcode3D proc

	ret
Opcode3D endp
; -----------------------------------------
; ------------ Opcode 0x3E ----------------
Opcode3E proc

	ret
Opcode3E endp
; -----------------------------------------
; ------------ Opcode 0x3F ----------------
Opcode3F proc

	ret
Opcode3F endp
; -----------------------------------------
; ------------ Opcode 0x40 ----------------
Opcode40 proc

	ret
Opcode40 endp
; -----------------------------------------
; ------------ Opcode 0x41 ----------------
Opcode41 proc

	ret
Opcode41 endp
; -----------------------------------------
; ------------ Opcode 0x42 ----------------
Opcode42 proc

	ret
Opcode42 endp
; -----------------------------------------
; ------------ Opcode 0x43 ----------------
Opcode43 proc

	ret
Opcode43 endp
; -----------------------------------------
; ------------ Opcode 0x44 ----------------
Opcode44 proc

	ret
Opcode44 endp
; -----------------------------------------
; ------------ Opcode 0x45 ----------------
Opcode45 proc

	ret
Opcode45 endp
; -----------------------------------------
; ------------ Opcode 0x46 ----------------
Opcode46 proc

	ret
Opcode46 endp
; -----------------------------------------
; ------------ Opcode 0x47 ----------------
Opcode47 proc
	ret
Opcode47 endp
; -----------------------------------------
; ------------ Opcode 0x48 ----------------
Opcode48 proc
	ret
Opcode48 endp
; -----------------------------------------
; ------------ Opcode 0x49 ----------------
Opcode49 proc

	ret
Opcode49 endp
; -----------------------------------------
; ------------ Opcode 0x4A ----------------
Opcode4A proc

	ret
Opcode4A endp
; -----------------------------------------
; ------------ Opcode 0x4B ----------------
Opcode4B proc

	ret
Opcode4B endp
; -----------------------------------------
; ------------ Opcode 0x4C ----------------
Opcode4C proc

	ret
Opcode4C endp
; -----------------------------------------
; ------------ Opcode 0x4D ----------------
Opcode4D proc

	ret
Opcode4D endp
; -----------------------------------------
; ------------ Opcode 0x4E ----------------
Opcode4E proc

	ret
Opcode4E endp
; -----------------------------------------
; ------------ Opcode 0x4F ----------------
Opcode4F proc

	ret
Opcode4F endp
; -----------------------------------------
; ------------ Opcode 0x50 ----------------
Opcode50 proc

	ret
Opcode50 endp
; -----------------------------------------
; ------------ Opcode 0x51 ----------------
Opcode51 proc

	ret
Opcode51 endp
; -----------------------------------------
; ------------ Opcode 0x52 ----------------
Opcode52 proc

	ret
Opcode52 endp
; -----------------------------------------
; ------------ Opcode 0x53 ----------------
Opcode53 proc

	ret
Opcode53 endp
; -----------------------------------------
; ------------ Opcode 0x54 ----------------
Opcode54 proc

	ret
Opcode54 endp
; -----------------------------------------
; ------------ Opcode 0x55 ----------------
Opcode55 proc

	ret
Opcode55 endp
; -----------------------------------------
; ------------ Opcode 0x56 ----------------
Opcode56 proc

	ret
Opcode56 endp
; -----------------------------------------
; ------------ Opcode 0x57 ----------------
Opcode57 proc

	ret
Opcode57 endp
; -----------------------------------------
; ------------ Opcode 0x58 ----------------
Opcode58 proc

	ret
Opcode58 endp
; -----------------------------------------
; ------------ Opcode 0x59 ----------------
Opcode59 proc

	ret
Opcode59 endp
; -----------------------------------------
; ------------ Opcode 0x5A ----------------
Opcode5A proc

	ret
Opcode5A endp
; -----------------------------------------
; ------------ Opcode 0x5B ----------------
Opcode5B proc

	ret
Opcode5B endp
; -----------------------------------------
; ------------ Opcode 0x5C ----------------
Opcode5C proc

	ret
Opcode5C endp
; -----------------------------------------
; ------------ Opcode 0x5D ----------------
Opcode5D proc

	ret
Opcode5D endp
; -----------------------------------------
; ------------ Opcode 0x5E ----------------
Opcode5E proc

	ret
Opcode5E endp
; -----------------------------------------
; ------------ Opcode 0x5F ----------------
Opcode5F proc

	ret
Opcode5F endp
; -----------------------------------------
; ------------ Opcode 0x60 ----------------
Opcode60 proc

	ret
Opcode60 endp
; -----------------------------------------
; ------------ Opcode 0x61 ----------------
Opcode61 proc

	ret
Opcode61 endp
; -----------------------------------------
; ------------ Opcode 0x62 ----------------
Opcode62 proc

	ret
Opcode62 endp
; -----------------------------------------
; ------------ Opcode 0x63 ----------------
Opcode63 proc

	ret
Opcode63 endp
; -----------------------------------------
; ------------ Opcode 0x64 ----------------
Opcode64 proc

	ret
Opcode64 endp
; -----------------------------------------
; ------------ Opcode 0x65 ----------------
Opcode65 proc

	ret
Opcode65 endp
; -----------------------------------------
; ------------ Opcode 0x66 ----------------
Opcode66 proc
	ret
Opcode66 endp
; -----------------------------------------
; ------------ Opcode 0x67 ----------------
Opcode67 proc

	ret
Opcode67 endp
; -----------------------------------------
; ------------ Opcode 0x68 ----------------
Opcode68 proc
		ret
Opcode68 endp
; -----------------------------------------
; ------------ Opcode 0x69 ----------------
Opcode69 proc

	ret
Opcode69 endp
; -----------------------------------------
; ------------ Opcode 0x6A ----------------
Opcode6A proc
		ret
Opcode6A endp
; -----------------------------------------
; ------------ Opcode 0x6B ----------------
Opcode6B proc

	ret
Opcode6B endp
; -----------------------------------------
; ------------ Opcode 0x6C ----------------
Opcode6C proc

	ret
Opcode6C endp
; -----------------------------------------
; ------------ Opcode 0x6D ----------------
Opcode6D proc

	ret
Opcode6D endp
; -----------------------------------------
; ------------ Opcode 0x6E ----------------
Opcode6E proc

	ret
Opcode6E endp
; -----------------------------------------
; ------------ Opcode 0x6F ----------------
Opcode6F proc

	ret
Opcode6F endp
; -----------------------------------------
; ------------ Opcode 0x70 ----------------
Opcode70 proc

	ret
Opcode70 endp
; -----------------------------------------
; ------------ Opcode 0x71 ----------------
Opcode71 proc

	ret
Opcode71 endp
; -----------------------------------------
; ------------ Opcode 0x72 ----------------
Opcode72 proc

	ret
Opcode72 endp
; -----------------------------------------
; ------------ Opcode 0x73 ----------------
Opcode73 proc

	ret
Opcode73 endp
; -----------------------------------------
; ------------ Opcode 0x74 ----------------
Opcode74 proc

	ret
Opcode74 endp
; -----------------------------------------
; ------------ Opcode 0x75 ----------------
Opcode75 proc

	ret
Opcode75 endp
; -----------------------------------------
; ------------ Opcode 0x76 ----------------
Opcode76 proc

	ret
Opcode76 endp
; -----------------------------------------
; ------------ Opcode 0x77 ----------------
Opcode77 proc

	ret
Opcode77 endp
; -----------------------------------------
; ------------ Opcode 0x78 ----------------
Opcode78 proc

	ret
Opcode78 endp
; -----------------------------------------
; ------------ Opcode 0x79 ----------------
Opcode79 proc

	ret
Opcode79 endp
; -----------------------------------------
; ------------ Opcode 0x7A ----------------
Opcode7A proc

	ret
Opcode7A endp
; -----------------------------------------
; ------------ Opcode 0x7B ----------------
Opcode7B proc

	ret
Opcode7B endp
; -----------------------------------------
; ------------ Opcode 0x7C ----------------
Opcode7C proc

	ret
Opcode7C endp
; -----------------------------------------
; ------------ Opcode 0x7D ----------------
Opcode7D proc

	ret
Opcode7D endp
; -----------------------------------------
; ------------ Opcode 0x7E ----------------
Opcode7E proc

	ret
Opcode7E endp
; -----------------------------------------
; ------------ Opcode 0x7F ----------------
Opcode7F proc

	ret
Opcode7F endp
; -----------------------------------------
; ------------ Opcode 0x80 ----------------
Opcode80 proc

	ret
Opcode80 endp
; -----------------------------------------
; ------------ Opcode 0x81 ----------------
Opcode81 proc

	ret
Opcode81 endp
; -----------------------------------------
; ------------ Opcode 0x82 ----------------
Opcode82 proc

	ret
Opcode82 endp
; -----------------------------------------
; ------------ Opcode 0x83 ----------------
Opcode83 proc

	ret
Opcode83 endp
; -----------------------------------------
; ------------ Opcode 0x84 ----------------
Opcode84 proc

	ret
Opcode84 endp
; -----------------------------------------
; ------------ Opcode 0x85 ----------------
Opcode85 proc

	ret
Opcode85 endp
; -----------------------------------------
; ------------ Opcode 0x86 ----------------
Opcode86 proc
	ret
Opcode86 endp
; -----------------------------------------
; ------------ Opcode 0x87 ----------------
Opcode87 proc

	ret
Opcode87 endp
; -----------------------------------------
; ------------ Opcode 0x88 ----------------
Opcode88 proc
	ret
Opcode88 endp
; -----------------------------------------
; ------------ Opcode 0x89 ----------------
Opcode89 proc
	ret
Opcode89 endp
; -----------------------------------------
; ------------ Opcode 0x8A ----------------
Opcode8A proc
	ret
Opcode8A endp
; -----------------------------------------
; ------------ Opcode 0x8B ----------------
Opcode8B proc
	ret
Opcode8B endp
; -----------------------------------------
; ------------ Opcode 0x8C ----------------
Opcode8C proc

	ret
Opcode8C endp
; -----------------------------------------
; ------------ Opcode 0x8D ----------------
Opcode8D proc

	ret
Opcode8D endp
; -----------------------------------------
; ------------ Opcode 0x8E ----------------
Opcode8E proc

	ret
Opcode8E endp
; -----------------------------------------
; ------------ Opcode 0x8F ----------------
Opcode8F proc

	ret
Opcode8F endp
; -----------------------------------------
; ------------ Opcode 0x90 ----------------
Opcode90 proc
	ret
Opcode90 endp
; -----------------------------------------
; ------------ Opcode 0x91 ----------------
Opcode91 proc

	ret
Opcode91 endp
; -----------------------------------------
; ------------ Opcode 0x92 ----------------
Opcode92 proc

	ret
Opcode92 endp
; -----------------------------------------
; ------------ Opcode 0x93 ----------------
Opcode93 proc

	ret
Opcode93 endp
; -----------------------------------------
; ------------ Opcode 0x94 ----------------
Opcode94 proc

	ret
Opcode94 endp
; -----------------------------------------
; ------------ Opcode 0x95 ----------------
Opcode95 proc

	ret
Opcode95 endp
; -----------------------------------------
; ------------ Opcode 0x96 ----------------
Opcode96 proc

	ret
Opcode96 endp
; -----------------------------------------
; ------------ Opcode 0x97 ----------------
Opcode97 proc

	ret
Opcode97 endp
; -----------------------------------------
; ------------ Opcode 0x98 ----------------
Opcode98 proc

	ret
Opcode98 endp
; -----------------------------------------
; ------------ Opcode 0x99 ----------------
Opcode99 proc

	ret
Opcode99 endp
; -----------------------------------------
; ------------ Opcode 0x9A ----------------
Opcode9A proc

	ret
Opcode9A endp
; -----------------------------------------
; ------------ Opcode 0x9B ----------------
Opcode9B proc

	ret
Opcode9B endp
; -----------------------------------------
; ------------ Opcode 0x9C ----------------
Opcode9C proc

	ret
Opcode9C endp
; -----------------------------------------
; ------------ Opcode 0x9D ----------------
Opcode9D proc

	ret
Opcode9D endp
; -----------------------------------------
; ------------ Opcode 0x9E ----------------
Opcode9E proc

	ret
Opcode9E endp
; -----------------------------------------
; ------------ Opcode 0x9F ----------------
Opcode9F proc

	ret
Opcode9F endp
; -----------------------------------------
; ------------ Opcode 0xA0 ----------------
OpcodeA0 proc

	ret
OpcodeA0 endp
; -----------------------------------------
; ------------ Opcode 0xA1 ----------------
OpcodeA1 proc

	ret
OpcodeA1 endp
; -----------------------------------------
; ------------ Opcode 0xA2 ----------------
OpcodeA2 proc

	ret
OpcodeA2 endp
; -----------------------------------------
; ------------ Opcode 0xA3 ----------------
OpcodeA3 proc

	ret
OpcodeA3 endp
; -----------------------------------------
; ------------ Opcode 0xA4 ----------------
OpcodeA4 proc

	ret
OpcodeA4 endp
; -----------------------------------------
; ------------ Opcode 0xA5 ----------------
OpcodeA5 proc

	ret
OpcodeA5 endp
; -----------------------------------------
; ------------ Opcode 0xA6 ----------------
OpcodeA6 proc

	ret
OpcodeA6 endp
; -----------------------------------------
; ------------ Opcode 0xA7 ----------------
OpcodeA7 proc

	ret
OpcodeA7 endp
; -----------------------------------------
; ------------ Opcode 0xA8 ----------------
OpcodeA8 proc

	ret
OpcodeA8 endp
; -----------------------------------------
; ------------ Opcode 0xA9 ----------------
OpcodeA9 proc

	ret
OpcodeA9 endp
; -----------------------------------------
; ------------ Opcode 0xAA ----------------
OpcodeAA proc

	ret
OpcodeAA endp
; -----------------------------------------
; ------------ Opcode 0xAB ----------------
OpcodeAB proc

	ret
OpcodeAB endp
; -----------------------------------------
; ------------ Opcode 0xAC ----------------
OpcodeAC proc

	ret
OpcodeAC endp
; -----------------------------------------
; ------------ Opcode 0xAD ----------------
OpcodeAD proc

	ret
OpcodeAD endp
; -----------------------------------------
; ------------ Opcode 0xAE ----------------
OpcodeAE proc

	ret
OpcodeAE endp
; -----------------------------------------
; ------------ Opcode 0xAF ----------------
OpcodeAF proc

	ret
OpcodeAF endp
; -----------------------------------------
; ------------ Opcode 0xB0 ----------------
OpcodeB0 proc

	ret
OpcodeB0 endp
; -----------------------------------------
; ------------ Opcode 0xB1 ----------------
OpcodeB1 proc

	ret
OpcodeB1 endp
; -----------------------------------------
; ------------ Opcode 0xB2 ----------------
OpcodeB2 proc

	ret
OpcodeB2 endp
; -----------------------------------------
; ------------ Opcode 0xB3 ----------------
OpcodeB3 proc

	ret
OpcodeB3 endp
; -----------------------------------------
; ------------ Opcode 0xB4 ----------------
OpcodeB4 proc

	ret
OpcodeB4 endp
; -----------------------------------------
; ------------ Opcode 0xB5 ----------------
OpcodeB5 proc

	ret
OpcodeB5 endp
; -----------------------------------------
; ------------ Opcode 0xB6 ----------------
OpcodeB6 proc

	ret
OpcodeB6 endp
; -----------------------------------------
; ------------ Opcode 0xB7 ----------------
OpcodeB7 proc

	ret
OpcodeB7 endp
; -----------------------------------------
; ------------ Opcode 0xB8 ----------------
OpcodeB8 proc
	ret
OpcodeB8 endp
; -----------------------------------------
; ------------ Opcode 0xB9 ----------------
OpcodeB9 proc

	ret
OpcodeB9 endp
; -----------------------------------------
; ------------ Opcode 0xBA ----------------
OpcodeBA proc

	ret
OpcodeBA endp
; -----------------------------------------
; ------------ Opcode 0xBB ----------------
OpcodeBB proc

	ret
OpcodeBB endp
; -----------------------------------------
; ------------ Opcode 0xBC ----------------
OpcodeBC proc

	ret
OpcodeBC endp
; -----------------------------------------
; ------------ Opcode 0xBD ----------------
OpcodeBD proc

	ret
OpcodeBD endp
; -----------------------------------------
; ------------ Opcode 0xBE ----------------
OpcodeBE proc

	ret
OpcodeBE endp
; -----------------------------------------
; ------------ Opcode 0xBF ----------------
OpcodeBF proc

	ret
OpcodeBF endp
; -----------------------------------------
; ------------ Opcode 0xC0 ----------------
OpcodeC0 proc

	ret
OpcodeC0 endp
; -----------------------------------------
; ------------ Opcode 0xC1 ----------------
OpcodeC1 proc

	ret
OpcodeC1 endp
; -----------------------------------------
; ------------ Opcode 0xC2 ----------------
OpcodeC2 proc

	ret
OpcodeC2 endp
; -----------------------------------------
; ------------ Opcode 0xC3 ----------------
OpcodeC3 proc

	ret
OpcodeC3 endp
; -----------------------------------------
; ------------ Opcode 0xC4 ----------------
OpcodeC4 proc

	ret
OpcodeC4 endp
; -----------------------------------------
; ------------ Opcode 0xC5 ----------------
OpcodeC5 proc

	ret
OpcodeC5 endp
; -----------------------------------------
; ------------ Opcode 0xC6 ----------------
OpcodeC6 proc
	ret
OpcodeC6 endp
; -----------------------------------------
; ------------ Opcode 0xC7 ----------------
OpcodeC7 proc
	ret
OpcodeC7 endp
; -----------------------------------------
; ------------ Opcode 0xC8 ----------------
OpcodeC8 proc

	ret
OpcodeC8 endp
; -----------------------------------------
; ------------ Opcode 0xC9 ----------------
OpcodeC9 proc

	ret
OpcodeC9 endp
; -----------------------------------------
; ------------ Opcode 0xCA ----------------
OpcodeCA proc

	ret
OpcodeCA endp
; -----------------------------------------
; ------------ Opcode 0xCB ----------------
OpcodeCB proc

	ret
OpcodeCB endp
; -----------------------------------------
; ------------ Opcode 0xCC ----------------
OpcodeCC proc

	ret
OpcodeCC endp
; -----------------------------------------
; ------------ Opcode 0xCD ----------------
OpcodeCD proc

	ret
OpcodeCD endp
; -----------------------------------------
; ------------ Opcode 0xCE ----------------
OpcodeCE proc

	ret
OpcodeCE endp
; -----------------------------------------
; ------------ Opcode 0xCF ----------------
OpcodeCF proc

	ret
OpcodeCF endp
; -----------------------------------------
; ------------ Opcode 0xD0 ----------------
OpcodeD0 proc

	ret
OpcodeD0 endp
; -----------------------------------------
; ------------ Opcode 0xD1 ----------------
OpcodeD1 proc

	ret
OpcodeD1 endp
; -----------------------------------------
; ------------ Opcode 0xD2 ----------------
OpcodeD2 proc

	ret
OpcodeD2 endp
; -----------------------------------------
; ------------ Opcode 0xD3 ----------------
OpcodeD3 proc

	ret
OpcodeD3 endp
; -----------------------------------------
; ------------ Opcode 0xD4 ----------------
OpcodeD4 proc

	ret
OpcodeD4 endp
; -----------------------------------------
; ------------ Opcode 0xD5 ----------------
OpcodeD5 proc

	ret
OpcodeD5 endp
; -----------------------------------------
; ------------ Opcode 0xD6 ----------------
OpcodeD6 proc

	ret
OpcodeD6 endp
; -----------------------------------------
; ------------ Opcode 0xD7 ----------------
OpcodeD7 proc

	ret
OpcodeD7 endp
; -----------------------------------------
; ------------ Opcode 0xD8 ----------------
OpcodeD8 proc

	ret
OpcodeD8 endp
; -----------------------------------------
; ------------ Opcode 0xD9 ----------------
OpcodeD9 proc

	ret
OpcodeD9 endp
; -----------------------------------------
; ------------ Opcode 0xDA ----------------
OpcodeDA proc

	ret
OpcodeDA endp
; -----------------------------------------
; ------------ Opcode 0xDB ----------------
OpcodeDB proc

	ret
OpcodeDB endp
; -----------------------------------------
; ------------ Opcode 0xDC ----------------
OpcodeDC proc

	ret
OpcodeDC endp
; -----------------------------------------
; ------------ Opcode 0xDD ----------------
OpcodeDD proc

	ret
OpcodeDD endp
; -----------------------------------------
; ------------ Opcode 0xDE ----------------
OpcodeDE proc

	ret
OpcodeDE endp
; -----------------------------------------
; ------------ Opcode 0xDF ----------------
OpcodeDF proc

	ret
OpcodeDF endp
; -----------------------------------------
; ------------ Opcode 0xE0 ----------------
OpcodeE0 proc

	ret
OpcodeE0 endp
; -----------------------------------------
; ------------ Opcode 0xE1 ----------------
OpcodeE1 proc

	ret
OpcodeE1 endp
; -----------------------------------------
; ------------ Opcode 0xE2 ----------------
OpcodeE2 proc

	ret
OpcodeE2 endp
; -----------------------------------------
; ------------ Opcode 0xE3 ----------------
OpcodeE3 proc

	ret
OpcodeE3 endp
; -----------------------------------------
; ------------ Opcode 0xE4 ----------------
OpcodeE4 proc

	ret
OpcodeE4 endp
; -----------------------------------------
; ------------ Opcode 0xE5 ----------------
OpcodeE5 proc

	ret
OpcodeE5 endp
; -----------------------------------------
; ------------ Opcode 0xE6 ----------------
OpcodeE6 proc

	ret
OpcodeE6 endp
; -----------------------------------------
; ------------ Opcode 0xE7 ----------------
OpcodeE7 proc

	ret
OpcodeE7 endp
; -----------------------------------------
; ------------ Opcode 0xE8 ----------------
OpcodeE8 proc

		ret
OpcodeE8 endp
; -----------------------------------------
; ------------ Opcode 0xE9 ----------------
OpcodeE9 proc

	ret
OpcodeE9 endp
; -----------------------------------------
; ------------ Opcode 0xEA ----------------
OpcodeEA proc

	ret
OpcodeEA endp
; -----------------------------------------
; ------------ Opcode 0xEB ----------------
OpcodeEB proc

	ret
OpcodeEB endp
; -----------------------------------------
; ------------ Opcode 0xEC ----------------
OpcodeEC proc

	ret
OpcodeEC endp
; -----------------------------------------
; ------------ Opcode 0xED ----------------
OpcodeED proc

	ret
OpcodeED endp
; -----------------------------------------
; ------------ Opcode 0xEE ----------------
OpcodeEE proc

	ret
OpcodeEE endp
; -----------------------------------------
; ------------ Opcode 0xEF ----------------
OpcodeEF proc

	ret
OpcodeEF endp
; -----------------------------------------
; ------------ Opcode 0xF0 ----------------
OpcodeF0 proc

	ret
OpcodeF0 endp
; -----------------------------------------
; ------------ Opcode 0xF1 ----------------
OpcodeF1 proc

	ret
OpcodeF1 endp
; -----------------------------------------
; ------------ Opcode 0xF2 ----------------
OpcodeF2 proc

	ret
OpcodeF2 endp
; -----------------------------------------
; ------------ Opcode 0xF3 ----------------
OpcodeF3 proc

	ret
OpcodeF3 endp
; -----------------------------------------
; ------------ Opcode 0xF4 ----------------
OpcodeF4 proc

	ret
OpcodeF4 endp
; -----------------------------------------
; ------------ Opcode 0xF5 ----------------
OpcodeF5 proc

	ret
OpcodeF5 endp
; -----------------------------------------
; ------------ Opcode 0xF6 ----------------
OpcodeF6 proc

	ret
OpcodeF6 endp
; -----------------------------------------
; ------------ Opcode 0xF7 ----------------
OpcodeF7 proc

	ret
OpcodeF7 endp
; -----------------------------------------
; ------------ Opcode 0xF8 ----------------
OpcodeF8 proc

	ret
OpcodeF8 endp
; -----------------------------------------
; ------------ Opcode 0xF9 ----------------
OpcodeF9 proc

	ret
OpcodeF9 endp
; -----------------------------------------
; ------------ Opcode 0xFA ----------------
OpcodeFA proc

	ret
OpcodeFA endp
; -----------------------------------------
; ------------ Opcode 0xFB ----------------
OpcodeFB proc

	ret
OpcodeFB endp
; -----------------------------------------
; ------------ Opcode 0xFC ----------------
OpcodeFC proc

	ret
OpcodeFC endp
; -----------------------------------------
; ------------ Opcode 0xFD ----------------
OpcodeFD proc

	ret
OpcodeFD endp
; -----------------------------------------
; ------------ Opcode 0xFE ----------------
OpcodeFE proc

	ret
OpcodeFE endp
; -----------------------------------------
; ------------ Opcode 0xFF ----------------
OpcodeFF proc

	ret
OpcodeFF endp
; -----------------------------------------
